// Generated by https://quicktype.io

export interface DataUser {
  nombre:          string;
  apellidop:       string;
  apellidom:       string;
  fecha: string;
  sexo:            string;
  telefono:        string;
  email:          string;
  nombreu:         string;
}
